# fly.toml file generated for comp7940-chatbot-group3 on 2023-04-04T00:12:48+08:00

app = "comp7940-chatbot-group3"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "hkg"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
